function [] = my_boxplot(x_index, array)
    
    alpha = 0.1;
    scatter(repmat(x_index,1,numel(array)), array, ...
            'k+', 'markeredgealpha', alpha, ... 
            'sizedata', 10, ...
            'markerfacecolor', 'k', ...
            'markerfacealpha', alpha, ...
            'linewidth', 0.01); hold on
    plot(x_index, median(array), 'k.','markersize', 15, 'linewidth',1); 
    hold on
    plot(repmat(x_index,1,2), ...
         [quantile(array,0.25), quantile(array,0.75)], ...
         'k.-','markersize', 12,'linewidth',1); 

    hold off
end